### ISSUE TITLE
Login is broken. 

### ISSUE THREAD

**Issue by SrOne** [Farfar/homeassistant-seatconnect#22] opened 2022-02-11 21:54 UTC
Hi, 
I update the homeassistant and after that reboot that stop to login. I have try two different main and sub-account account and result is same. Visit from my.seat/portal but no any accept forms appear. 

Logbook: 
 2022-02-11 21:29:39 DEBUG (MainThread) [seatconnect.connection] Finalizing login
2022-02-11 21:29:39 DEBUG (MainThread) [seatconnect.connection] Using login action url: "https://identity.vwgroup.iologin/authenticate"
2022-02-11 21:29:39 DEBUG (MainThread) [seatconnect.connection] POSTing following form data: {'_csrf': '05856c02-xxxreplacewithxxx2-4c41-8726-20xreplacewithxf92fe23d', 'relayState': 'df9ce90c83fbf4xxxxxc13b3b3c45498xxreplacewithxxd206a', 'hmac': '492e2xxxxx0f83b7e23096bdb4d9edxxxreplacewithxxxa219c40fc02161284e9a0ba', 'email': '*mymail*@gmail.com', 'password': '*rightpassword*'}
2022-02-11 21:29:39 ERROR (MainThread) [seatconnect.connection] Login failed for *mymail*@gmail.com, Cannot connect to host identity.vwgroup.iologin:443 ssl:default [Name does not resolve]
2022-02-11 21:29:39 DEBUG (MainThread) [custom_components.seatconnect.config_flow] Unable to login to Seat Connect. Need to accept a new EULA/T&C? Try logging in to the portal: https://my.seat/portal

**Comment by DrIc03R** [comment] 2022-02-11 22:30
<img width="426" alt="2022-02-11 23_21_11-Einstellungen – Home Assistant" src="https://user-images.githubusercontent.com/99083098/153679546-d7184782-a8c5-4f72-88a8-f097f95c51eb.png">

Hi Farfar, 

I got the same issue this evening.

I think the problem is, that there is a missing "/" in the URL:
https://identity.vwgroup.iologin/authenticate

vwgroup.iologin is not a valid domain.

At the moment I'm trying to understand the code to find a solution to fix this problem.

**Comment by enricog03** [comment] 2022-02-12 11:38
Same issue here after HA update!

**Comment by Pulpyyyy** [comment] 2022-02-12 12:49
@DrIc03R seems right 
Looks better with /
![image](https://user-images.githubusercontent.com/32004297/153712041-fe3d7e11-d481-43a3-adc1-f3bfd7f06cc0.png)

**Comment by enricog03** [comment] 2022-02-12 13:29
I tried adding the missing "/" to the connections.py file. 

`2022-02-12 14:20:57 DEBUG (MainThread) [seatconnect.connection] Using login action url: "https://identity.vwgroup.io/login/authenticate"`

But it doesn't work anyway, I got a different error.

`2022-02-12 14:20:57 WARNING (MainThread) [seatconnect.connection] Login failed for ******. The server might be temporarily unavailable, try again later. If the problem persists, verify your account at https://my.seat/portal/
2022-02-12 14:20:57 INFO (MainThread) [seatconnect.connection] Token validation failed, Could not extract exp attribute
2022-02-12 14:20:57 DEBUG (MainThread) [seatconnect.connection] Tokens for "seat" are invalid
2022-02-12 14:20:57 DEBUG (MainThread) [seatconnect.connection] Refreshing tokens for client "seat"
2022-02-12 14:20:57 WARNING (MainThread) [seatconnect.connection] Could not refresh tokens: 'seat'
2022-02-12 14:20:57 DEBUG (MainThread) [seatconnect.connection] Could not fetch consent information. If problems are encountered please visit the web portal first and make sure that no new terms and conditions need to be accepted.
2022-02-12 14:20:57 DEBUG (MainThread) [seatconnect.connection] Client "vwg" token is missing, call to authorize the client.
2022-02-12 14:20:57 DEBUG (MainThread) [seatconnect.connection] Token is missing, call to authorize the client.`

**Comment by enricog03** [comment] 2022-02-12 14:22
I solved the issue manually merging the changes from last skodaconnect library commit in my HA.

https://github.com/lendy007/skodaconnect/commit/0714de01ab470be9e276bb68860b81b4dae0fbb4

I think that Farfar will update the main branch soon.

**Comment by tulkarxxx** [comment] 2022-02-12 19:53
Same issue for me after HA update

**Comment by DrIc03R** [comment] 2022-02-12 22:36
> I solved the issue manually merging the changes from the skodaconnect library commit in my HA.
> 
> [lendy007/skodaconnect@0714de0](https://github.com/lendy007/skodaconnect/commit/0714de01ab470be9e276bb68860b81b4dae0fbb4)
> 
> I think that Farfar will update the main branch soon.

Hi enricog03,

thanks for the hint, I managed to get through the authentication by merging with skodaconnect, but I'm stuck by fetching vehicles. At this part, there are some differences between skodaconnect and seatconnect, I do not get managed to merge. 

Do you think, you're willing to share you're merged files? This would be an enormous help.
Thank you.

**Comment by enricog03** [comment] 2022-02-13 00:57
> > I solved the issue manually merging the changes from the skodaconnect library commit in my HA.
> > [lendy007/skodaconnect@0714de0](https://github.com/lendy007/skodaconnect/commit/0714de01ab470be9e276bb68860b81b4dae0fbb4)
> > I think that Farfar will update the main branch soon.
> 
> Hi enricog03,
> 
> thanks for the hint, I managed to get through the authentication by merging with skodaconnect, but I'm stuck by fetching vehicles. At this part, there are some differences between skodaconnect and seatconnect, I do not get managed to merge.
> 
> Do you think, you're willing to share you're merged files? This would be an enormous help. Thank you.

Hi, 
you can download my connection.py file below. You need to put it in the "/usr/local/lib/python3.9/site-packages/seatconnect/" path of your HA instance.
I think it will be overwritten with every HA update, so I hope Farfar will update the official version.

[connection.zip](https://github.com/Farfar/homeassistant-seatconnect/files/8054761/connection.zip)

**Comment by DrIc03R** [comment] 2022-02-14 13:42
> > > I solved the issue manually merging the changes from the skodaconnect library commit in my HA.
> > > [lendy007/skodaconnect@0714de0](https://github.com/lendy007/skodaconnect/commit/0714de01ab470be9e276bb68860b81b4dae0fbb4)
> > > I think that Farfar will update the main branch soon.
> > 
> > 
> > Hi enricog03,
> > thanks for the hint, I managed to get through the authentication by merging with skodaconnect, but I'm stuck by fetching vehicles. At this part, there are some differences between skodaconnect and seatconnect, I do not get managed to merge.
> > Do you think, you're willing to share you're merged files? This would be an enormous help. Thank you.
> 
> Hi, you can download my connection.py file below. You need to put it in the "/usr/local/lib/python3.9/site-packages/seatconnect/" path of your HA instance. I think it will be overwritten with every HA update, so I hope Farfar will update the official version.
> 
> [connection.zip](https://github.com/Farfar/homeassistant-seatconnect/files/8054761/connection.zip)

Thank you! Works great again.

**Comment by HerrmannsdoerferS** [comment] 2022-02-15 06:41
Hi,
maybe a silly question, but if i navigate to the folder "/usr/local/lib/" there is no folder "python3.9".
What i'm doing wrong?

any help appreciated

**Comment by oneofthemany** [comment] 2022-02-15 10:13
> Hi, maybe a silly question, but if i navigate to the folder "/usr/local/lib/" there is no folder "python3.9". What i'm doing wrong?
> 
> any help appreciated

try here:

/config/deps/lib/python3.9/site-packages/seatconnect/

**Comment by HerrmannsdoerferS** [comment] 2022-02-15 11:28
thanks for the reply, but same thing as mentioned above, no folder when connecting with sftp.
im running this ha setting:
![image](https://user-images.githubusercontent.com/66716371/154052972-89ca1fc8-8235-4672-8ef8-cbe3e22f094b.png)

so when i enter the container which runs tagged as homeassistant i could find this folder. but i have no clue ho to exchange this file without crashing my system

**Comment by DrIc03R** [comment] 2022-02-15 12:07
> 

If you're using docker based HA try the following:

1. SSH to the OS (you must have activated ssh in the terminal plugin you find in supervised addon store)
2. Run  "exec -it homeassistant bash"
Now you have access to the console in the docker container.  Try again to find the folder /usr/local/lib/python3.9/site-packages/seatconnect

**Comment by DrIc03R** [comment] 2022-02-15 12:25
> thanks for the reply, but same thing as mentioned above, no folder when connecting with sftp. im running this ha setting: ![image](https://user-images.githubusercontent.com/66716371/154052972-89ca1fc8-8235-4672-8ef8-cbe3e22f094b.png)
> 
> so when i enter the container which runs tagged as homeassistant i could find this folder. but i have no clue ho to exchange this file without crashing my system

Sorry didn't read your last sentence.

I did the following:
1. Rename the original connection.py to connection.bak 
2. Create the file new with "vi connection.py"
3. Open the connection.py by enricog03 in an GUI Editor of you choice an copy the whole content to the clipboard.
3. Go into insert mode in vi and copy the whole content of the connection.py by enricog03 into vi by right click.
4. Leave insert mode with "ESC" and save with :wq 
5. Restart your HA Core

Working with the connection.py while HA ist running, will not crash the system.

**Comment by HerrmannsdoerferS** [comment] 2022-02-15 15:07
> > thanks for the reply, but same thing as mentioned above, no folder when connecting with sftp. im running this ha setting: ![image](https://user-images.githubusercontent.com/66716371/154052972-89ca1fc8-8235-4672-8ef8-cbe3e22f094b.png)
> > so when i enter the container which runs tagged as homeassistant i could find this folder. but i have no clue ho to exchange this file without crashing my system
> 
> Sorry didn't read your last sentence.
> 
> I did the following:
> 
> 1. Rename the original connection.py to connection.bak
> 2. Create the file new with "vi connection.py"
> 3. Open the connection.py by enricog03 in an GUI Editor of you choice an copy the whole content to the clipboard.
> 4. Go into insert mode in vi and copy the whole content of the connection.py by enricog03 into vi by right click.
> 5. Leave insert mode with "ESC" and save with :wq
> 6. Restart your HA Core
> 
> Working with the connection.py while HA ist running, will not crash the system.

THANKS for the great explanation!!! 🥇 
now it works again 👍

**Comment by oneofthemany** [comment] 2022-02-15 21:07
if you're running a container - as I am albeit in podman  and not docker - the location is as above in the config folder:

/config/deps/lib/python3.9/site-packages/seatconnect/

it is potentially easier to just cd to the folder location above and then:

`wget https://github.com/Farfar/homeassistant-seatconnect/files/8054761/connection.zip && unzip connection.zip && rm connection.zip && docker restart homeassistant`

**Comment by xrado** [comment] 2022-02-16 21:15
@Farfar still here?

**Comment by Farfar** [comment] 2022-02-17 08:04
Fixed in latest release 👍🏼

**Closed as completed by Farfar** 2022-02-17 08:04 UTC
