### ISSUE TITLE
Log Warning: SOURCE_TYPE_GPS

### ISSUE THREAD

**Issue by MarcFu** [Farfar/homeassistant-seatconnect#55] opened 2024-04-28 09:58 UTC
It seems that some Home Assistant constants will change in the future. It looks as if there is a drop-in-replacement.

Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:206
integration: Device tracker (documentation, issues)
First occurred: 11:53:15 (2 occurrences)
Last logged: 11:53:15

SOURCE_TYPE_GPS was used from seatconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please report it to the author of the 'seatconnect' custom integration

**Comment by z-master42** [comment] 2024-07-09 16:03
Duplicate of #49.

**Comment by Farfar** [comment] 2024-10-07 08:55
This code is no longer being maintained by me and requires contributors in order to fix issues.

**Closed as completed by Farfar** 2024-10-07 08:55 UTC
