### ISSUE TITLE
not work since 23 September

### ISSUE THREAD

**Issue by yoku70** [Farfar/homeassistant-seatconnect#6] opened 2021-09-23 18:09 UTC
It does not work since 23 September, my user's connection is no longer recognized, while on the official app it continues to work regularly

**Comment by Farfar** [comment] 2021-09-23 19:04
Duplicate of #4

**Comment by Farfar** [comment] 2021-09-24 14:18
Closing this issue now since initial testing of 1.1.0 seems to have solved the problems for others. If there's any problems with 1.1.0 version it should be a new issue.

**Closed as completed by Farfar** 2021-09-24 14:18 UTC
