### ISSUE TITLE
it stopped working

### ISSUE THREAD

**Issue by VictorDuenasIllana** [Farfar/homeassistant-seatconnect#5] opened 2021-09-23 09:18 UTC
Since last 22/09/21 Seat Connect does not work with home assistant. I've tried rewritting configuration in configuration.yaml and also reinstalled the integration but this could not make it work.

Please try to fix the problem, some charging automations depend on Seat Connect.

Thanks for yor work for the communitty

**Comment by Farfar** [comment] 2021-09-23 19:04
Duplicate of #4

**Comment by Farfar** [comment] 2021-09-24 14:18
Closing this issue now since initial testing of 1.1.0 seems to have solved the problems for others. If there's any problems with 1.1.0 version it should be a new issue.

**Closed as completed by Farfar** 2021-09-24 14:18 UTC

**Comment by VictorDuenasIllana** [comment] 2021-09-26 20:28
Thanks so much for your effort and job. It now works perfectly.
