### ISSUE TITLE
after update no login possible

### ISSUE THREAD

**Issue by kevinpaulus** [Farfar/homeassistant-seatconnect#23] opened 2022-02-16 15:40 UTC
After updating HA, the login no longer works. It will show error "Login failed for info@XX, Cannot connect to host identity.vwgroup.iologin:443 ssl:default [Name does not resolve]" in the log. Unfortunately, solving "@[DrIc03R]" doesn't help either. Please update, thanks in advance.

**Comment by Farfar** [comment] 2022-02-17 08:01
Duplicate of #22

**Closed as completed by Farfar** 2022-02-17 08:01 UTC
