### ISSUE TITLE
Cannot connect to host - Name does not resolve

### ISSUE THREAD

**Issue by xrado** [Farfar/homeassistant-seatconnect#21] opened 2022-02-11 21:51 UTC
Stopped to work a day or two ago. My credentials are working fine on my.seat/portal. Any Idea what could it be?
```
2022-02-11 22:43:00 ERROR (MainThread) [seatconnect.connection] Login failed for my_email, Cannot connect to host identity.vwgroup.iologin:443 ssl:default [Name does not resolve]
2022-02-11 22:43:00 WARNING (MainThread) [custom_components.seatconnect] Could not login to Seat Connect, please check your credentials and verify that the service is working
```

**Comment by Farfar** [comment] 2022-02-17 08:04
Duplicate of #22

**Closed as completed by Farfar** 2022-02-17 08:04 UTC
